import {Nunito} from "next/font/google"
import './globals.css'
import Navbar from "@/app/components/navbar/Navbar";
import RegisterModal from "@/app/components/Modal/RegisterModal";
import ToasterProvider from "@/app/providers/ToasterProvider";
import LoginModal from "@/app/components/Modal/LoginModal";
import getCurrentUser from "@/app/actions/getCurrentUser";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

//Google font optimisation in next.js
//https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
const font = Nunito({
    subsets: ["latin"]
})

export default async function RootLayout({children}: {
    children: React.ReactNode
}) {
    const currentUser = await getCurrentUser()
    return (
        <html lang="en">
        <body className={font.className}>
        <ToasterProvider/>
        <LoginModal/>
        <RegisterModal/>
        <Navbar currentUser={currentUser}/>
        {children}
        </body>
        </html>
    )
}
